##NUMPY

In [4]:
import numpy as np

In [ ]:
##CREATING ARRAY FROM LIST 

arr_1d = np.array([1,2,3,4,5,6])
print("Numpy 1D Array",arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("Numpy 2D Array",arr_2d)

arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Numpy 3D Array",arr_3d)

Numpy 1D Array [1 2 3 4 5 6]
Numpy 2D Array [[1 2 3]
 [4 5 6]]
Numpy 3D Array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
##LIST VS NUMPY ARRAY

py_list = [1,2,3,4,5]
print("Python List Multiplication : " , py_list * 2)


np_array = np.array([1,2,3,4,5])
print("Numpy Array Multiplication : " , np_array * 2)

Python List Multiplication :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array Multiplication :  [ 2  4  6  8 10]


In [ ]:
## LIST AND NUMPY DIFFRENSE TIME 

import time

start = time.time()
py_array = [i*2 for i in range(100000)]
print("\n Python Operation time : ",time.time() - start)


start = time.time()
np_array = np.arange(10000) * 2 
print("\n Numpy Operation time : ",time.time() - start)



 Python Operation time :  0.005999565124511719

 Numpy Operation time :  0.0


In [ ]:
##CREATING ARRAY FROM SCRATCH

zeros = np.zeros([4,5])
print("\n ZEROS ARRAY \n",zeros)

ones = np.ones([5,5])
print("\n ONES ARRAY\n" , ones)

full = np.full([4,5],8)
print("\n FULL ARRAY \n" , full)

random = np.random.random([5,5])
print("\n RANDON ARRAY \n" , random)

sequence = np.arange(0,20,2)
print("\nSEQUENCE ARRAY \n" , sequence)


 ZEROS ARRAY 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 ONES ARRAY
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 FULL ARRAY 
 [[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]

 RANDON ARRAY 
 [[0.85810068 0.52154919 0.95717516 0.97277529 0.54502047]
 [0.47511016 0.36168742 0.63017402 0.26867397 0.1584083 ]
 [0.94701644 0.25172568 0.00130545 0.85632936 0.66899021]
 [0.67230676 0.79031191 0.8971928  0.57443051 0.80793582]
 [0.39451539 0.57170834 0.91735758 0.60809091 0.15703212]]

SEQUENCE ARRAY 
 [ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
## VECTOR , MATRIX  AND TENSOR ARRAY 

vector =np.array([1,2,3,4,5,6,7,8,9,10])
print("\n VECTOR ARRAY \n" , vector)

matrix = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\n MATRIX ARRAY \n" , matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n TENSOR ARRAY \n" , tensor)



 VECTOR ARRAY 
 [ 1  2  3  4  5  6  7  8  9 10]

 MATRIX ARRAY 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 TENSOR ARRAY 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
## ARRAY PROPERTIES

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print("SHAPE : ", arr.shape)
print("DIMENSION : ", arr.ndim)
print("Dtype : " , arr.dtype)
print("SIZE : ",arr.size)
print("ITEM SIZE : " , arr.itemsize)
print("DATA : ", arr.data)

SHAPE :  (2, 5)
DIMENSION :  2
Dtype :  int64
SIZE :  10
ITEM SIZE :  8
DATA :  <memory at 0x0000020CCFD6A5A0>


In [ ]:
##ARRAY RESHAPING

arr = np.arange(12)
print("\n ORIGNAL ARRAY : " , arr)

reshaped = arr.reshape((3,4))
print("\n RESHAPED ARRAY : " , reshaped)

Flattend = arr.flatten()
print("\n FLATTENED ARRAY : " , Flattend)

ravel = reshaped.ravel()
print("\n RAVEL ARRAY : " , ravel)

transpose = reshaped.T
print("\n TRANSPOSED ARRAY : ", transpose)


 ORIGNAL ARRAY :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 RESHAPED ARRAY :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 FLATTENED ARRAY :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 RAVEL ARRAY :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 TRANSPOSED ARRAY :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
