NUMPY ARRAY OPERATION

In [2]:
import numpy as np

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("\nBASIC SLICING : " ,arr[2:6])
print("\nWITH STEPS : " , arr[1:8:2])
print("\nNEGATIVE INDEXING : ", arr[-3])



BASIC SLICING :  [3 4 5 6]

WITH STEPS :  [2 4 6 8]

NEGATIVE INDEXING :  18


In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nSPECIFIC ELEMENT : ",arr_2d[1,2])
print("\nENTIRE ROW : " , arr_2d[1])
print("\nENTIRE COLUMN : ", arr_2d[: , 1])



SPECIFIC ELEMENT :  6

ENTIRE ROW :  [4 5 6]

ENTIRE COLUMN :  [2 5 8]


In [12]:
unsorted = np.array([1,5,9,5,3,4,1,2,6,7])
print("\n SORTED ARRAY : ",np.sort(unsorted))

arr_2d = np.array([[1,4],
                   [1,3],
                   [2,3]])
print("\n 2D ARRAY COLOUMN WISE SORTING : " , np.sort(arr_2d , axis=0))
print("\n 2D ARRAY ROW WISE SORTING : " , np.sort(arr_2d , axis=1))




 SORTED ARRAY :  [1 1 2 3 4 5 5 6 7 9]

 2D ARRAY COLOUMN WISE SORTING :  [[1 3]
 [1 3]
 [2 4]]

 2D ARRAY ROW WISE SORTING :  [[1 4]
 [1 3]
 [2 3]]


In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = arr[arr % 2 == 0]
print("\n EVEN NUMBERS " ,even_number)


 EVEN NUMBERS  [ 2  4  6  8 10]


In [19]:
arr_mask = np.array([1,2,3,4,5,6,7,8,9,10])
mask = arr_mask > 5
print("\n GREATE THAN 5 : ", arr_mask[mask])


 GREATE THAN 5 :  [ 6  7  8  9 10]


In [24]:
ind_arr = np.array([1,2,3,4,5,6,8,9,10])
indices = [0,2,4]
print("\n INDICES ARRAY : " ,ind_arr[indices])

where_res = np.where(ind_arr > 5)
print("\n WHERE RESSULT : ", ind_arr[where_res])


 INDICES ARRAY :  [1 3 5]

 WHERE RESSULT :  [ 6  8  9 10]


In [27]:
cond_arr = np.array([1,2,3,4,5,6,7,8,9,10])
conditon_arr = np.where(cond_arr > 5 , cond_arr*2 , cond_arr)
print("\n CONDITION ARRAY : " , conditon_arr)


 CONDITION ARRAY :  [ 1  2  3  4  5 12 14 16 18 20]


In [33]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

add_arr = arr_1 + arr_2
print("\n ADDIND 2 ARRAYS : " , add_arr)
print("\n COMBINING 2 ARRAYS : ", np.concatenate((arr_1 ,arr_2 )))


 ADDIND 2 ARRAYS :  [ 7  9 11 13 15]

 COMBINING 2 ARRAYS :  [ 1  2  3  4  5  6  7  8  9 10]


In [37]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
new_row= np.array([7,8,9])
print("\n WITH NEW ROW \n ", np.vstack((arr_2d , new_row)))


arr_1d = np.array([1,2,3,4,5])
new_col = np.array([6,7,8,9,10])
print("\n WITH NEW COLUN \n ", np.hstack((arr_1d , new_col)))


 WITH NEW ROW 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]

 WITH NEW COLUN 
  [ 1  2  3  4  5  6  7  8  9 10]


In [41]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete(arr_1 , 2)
print("\n ARRAY BEFORE DELETION : " , arr_1)
print("\n ARRAY AFTER DELETION : " , deleted)


 ARRAY BEFORE DELETION :  [ 1  2  3  4  5  6  7  8  9 10]

 ARRAY AFTER DELETION :  [ 1  2  4  5  6  7  8  9 10]
